#
# Copyright (C) 2023 TDT AG <development@tdt.de>
#
# This is free software, licensed under the Apache License Version 2.0.
# See https://www.apache.org/licenses/LICENSE-2.0 for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-notification
PKG_RELEASE:=1.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Florian Eckert <fe@dev.tdt.de>

LUCI_TITLE:=LuCI support for system notifications
LUCI_DEPENDS:=system-notification
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
